name:                mbox-chat
version:             0.1.0.0
github:              "githubuser/mbox-chat"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mbox-chat#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pipes
- time

library:
  source-dirs: src

ghc-options:
  - -Wall

executables:
  mbox-chat-exe:
    main:                Main.hs
    source-dirs:         app/getids
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - mbox-chat
    - hashtables
    - pipes-text
    - pipes-safe
    - containers
    - text
  mbox-chat-split-exe:
    main:                Main.hs
    source-dirs:         app/splitchats
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - mbox-chat
    - hashtables
    - pipes-text
    - pipes-safe
    - containers
    - text
